const clinics = [
    {
      name: "CBD Health Office",
      address: "CJ Cronjé Building, 6th Floor South Wing, 80 Loveday Street, Cnr Plein Street, Johannesburg",
      tel: ["011 376 8525", "011 376 8554"],
      openingTime: "8:00 AM",
      closingTime: "4:30 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: true, // Not provided
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Urban Health",
      address: "Ground Floor, CJ Cronjé Building, 80 Loveday Street, Johannesburg, 2001",
      tel: ["011 336 5241", "011 336 5243"],
      openingTime: "8:00 AM",
      closingTime: "4:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Mayfair",
      address: "Corner Sumner Street and Ninth Avenue, 35 Bartlett Rd, Mayfair West, Johannesburg, 2092",
      tel: "011 837 6206",
      openingTime: "8:00 AM",
      closingTime: "4:00 PM",
      specialties: [
        "Diabetes",
        "Dialysis",
        "HIV",
        "Hypertension",
        "Medical Nutrition",
        "Renal Failure",
        "Weight Loss",
      ],
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Joubert Park",
      address: "Corner Twist and Wolmarans Streets, Joubert Park, Johannesburg",
      tel: "011 725 4728",
      openingTime: "8:00 AM",
      closingTime: "4:00 PM",
      specialties: [],
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Jeppe",
      address: "34 Ford Street, Jeppestown, 2094",
      tel: ["011 614 1474", "011 614 1475", "011 614 1476"],
      openingTime: "8:00 AM",
      closingTime: "4:00 PM",
      specialties: ["TB", "Psychiatry"],
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Esselen Street HIV/Aids Programme",
      address: "17 Esselen St, Hillbrow, Johannesburg, 2001",
      tel: ["011 725 6711", "011 725 6721"],
      openingTime: "8:00 AM",
      closingTime: "4:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Yeoville",
      address: "Corner Kenmere and Hopkins Streets, Yeoville, Johannesburg, 2198",
      tel: "011 648 7979",
      openingTime: "8:00 AM",
      closingTime: "4:00 PM",
      specialties: ["TB"],
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Cardiac Rehabilitation and Exercise",
      address: "Wits Education Campus (JCE), St Andrews Road, Parktown",
      tel: ["011 717 3376", "011 717 3377"],
      openingTime: "7:00 AM",
      closingTime: "7:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Rosettenville",
      address: "1 Rose Avenue, Cnr Mabel Street, Rosettenville, 2190",
      tel: ["011 435 1045", "011 435 1046", "011 435 1047"],
      openingTime: "7:30 AM",
      closingTime: "4:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Glenanda",
      address: "Corner Vorster Avenue and Surmone Street, Glenanda",
      tel: "011 432 3546",
      openingTime: "7:30 AM",
      closingTime: "3:30 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: "info@glenandamedicalcentre.co.za",
      website: null, // Facebook page provided instead
    },
    {
      name: "South Hills",
      address: "Corner Geneva and Estantia Roads, Welfare Park, Johannesburg South, 2197",
      tel: "011 623 1297",
      openingTime: "7:30 AM",
      closingTime: "4:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Crown Gardens",
      address: "Recreation Centre, Cnr Ulster and Mourne Streets, Crown Gardens, Johannesburg South, 2091",
      tel: "011 433 2351",
      openingTime: "8:00 AM",
      closingTime: "4:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Bellavista",
      address: "Corner Zietsman and Alex Streets, Bellavista",
      tel: "011 433 1593",
      openingTime: "7:30 AM",
      closingTime: "2:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Malvern",
      address: "501 – 505 Malvern Plaza, Malvern",
      tel: "011 622 1245",
      openingTime: "7:30 AM",
      closingTime: "4:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Kibler Park",
      address: "Corner Kenneth Gardens and Summer Place, Kibler Park, 2091",
      tel: "011 943 2002",
      openingTime: "7:30 AM",
      closingTime: "4:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Crosby Clinic",
      address: "Stand 1629, 77 Ingelby Street, Crosby",
      tel: ["011 837 9118", "011 837 9119"],
      openingTime: "7:30 AM",
      closingTime: "4:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Jeppe Street Clinic",
      address: "1429 Johannesburg 159 Rahima Moosa Street (previously Jeppe Street), Jeppe Street, Johannesburg",
      tel: "011 336 0517",
      openingTime: "7:00 AM",
      closingTime: "4:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Bezvalley Clinic",
      address: "1316 Bezuidenhout Valley, Cnr 6th Street & 4th Ave, Bezvalley",
      tel: "011 648 0617",
      openingTime: "7:30 AM",
      closingTime: "4:00 PM",
      specialties: [], // Not provided
      isClinic: true,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
  ];

  const hospitals = [
    {
      name: "Life Bedford Gardens Hospital",
      address: "7 Leicester Road, Bedford Gardens, Bedfordview, 2008",
      tel: "011 677 8500",
      openingTime: null, // Not provided
      closingTime: null, // Not provided
      specialties: [], // Not provided
      isClinic: false,
      public: true,
      open24Hours: false, // Not provided
      email: "Nozuko.Daweti@lifehealthcare.co.za",
      website: "https://www.lifehealthcare.co.za/hospitals/gauteng/johannesburg/life-bedford-gardens-hospital/",
    },
    {
      name: "Life Brackenview",
      address: "22 De Waal Street, Brackendowns, Alberton",
      tel: "010 009 6200",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: false,
      email: [
        "info.brackenview@lifehealthcare.co.za",
        "ashni.Padiachey@lifehealthcare.co.za",
      ],
      website: "https://www.lifehealthcare.co.za/hospitals/gauteng/johannesburg/life-brackenview/",
    },
    {
      name: "Life Brenthurst Hospital",
      address: "4 Park Lane, Parktown, Johannesburg, 2193",
      tel: "011 647 9000",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: false,
      email: "Brenthurst.Communication@lifehealthcare.co.za",
      website: "https://www.lifehealthcare.co.za/hospitals/gauteng/johannesburg/life-brenthurst-hospital/",
    },
    {
      name: "Chris Hani Baragwanath Hospital",
      address: "26 Chris Hani Road, Bertsham, Johannesburg",
      tel: "011 933 8000",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: false,
      email: null,
      website: "http://www.chrishanibaragwanathhospital.co.za/",
    },
    {
      name: "Helen Joseph Hospital",
      address: "1 Perth Road, Auckland Park, Johannesburg",
      tel: "011 489 1011",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: true,
      email: null,
      website: null,
    },
    {
      name: "Charlotte Maxeke Johannesburg Academic Hospital",
      address: "17 Jubilee Road, Parktown, Johannesburg",
      tel: "011 488 4911",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: true,
      email: "Angy.Mokgothu@gauteng.gov.za",
      website: null, // Facebook page provided instead
    },
    {
      name: "Rahima Moosa Mother and Child Hospital",
      address: "Fule Street & Oudtshoorn Street, Newclare, Johannesburg",
      tel: "011 470 9000",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Edenvale General Hospital",
      address: "Modderfontein Road, Edenvale, Johannesburg",
      tel: "011 321 6000",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Tambo Memorial Hospital",
      address: "Railway Street, Boksburg, Johannesburg",
      tel: "011 898 8000",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Lenasia South Hospital",
      address: "Marlin Avenue, Lenasia South, Johannesburg",
      tel: "011 213 2000",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "South Rand Hospital",
      address: "Friars Hill Road, Rosettenville, Johannesburg South",
      tel: "011 435 0022",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Tembisa Hospital",
      address: "Industry Road, Olifantsfontein, Tembisa",
      tel: "011 923 2000",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: true,
      open24Hours: false,
      email: null,
      website: null,
    },
    {
      name: "Far East Rand Hospital",
      address: "Hospital Street, Springs, Johannesburg",
      tel: "011 812 8300",
      openingTime: null,
      closingTime: null,
      specialties: [],
      isClinic: false,
      public: false,
      open24Hours: false,
      email: null,
      website: null,
    },
  ];
  
export {clinics,hospitals}   