const clinics = [
  {
    id: 1,
    name: "CBD Health Office",
    address:
      "CJ Cronjé Building, 6th Floor South Wing, 80 Loveday Street, Cnr Plein Street, Johannesburg",
    tel: ["011 376 8525"],
    openingTime: "8:00 AM",
    closingTime: "4:30 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: true, // Not provided
    open24Hours: false,
    email: null,
    website: null,
    emergencyRooms: true,
    capacity: "25%",
  },
  {
    id: 2,
    name: "Urban Health",
    address:
      "Ground Floor, CJ Cronjé Building, 80 Loveday Street, Johannesburg, 2001",
    tel: ["011 336 5241", "011 336 5243"],
    openingTime: "8:00 AM",
    closingTime: "4:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
    emergencyRooms: true,
    capacity: "50%",
  },
  {
    id: 3,
    name: "Mayfair",
    address:
      "Corner Sumner Street and Ninth Avenue, 35 Bartlett Rd, Mayfair West, Johannesburg, 2092",
    tel: ["011 837 6206"],
    openingTime: "8:00 AM",
    closingTime: "4:00 PM",
    Specialties: [
      "Diabetes",
      "Dialysis",
      "HIV",
      "Hypertension",
      "Medical Nutrition",
      "Renal Failure",
      "Weight Loss",
    ],
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
    emergencyRooms: false,
    capacity: "100%",
  },
  {
    id: 4,
    name: "Joubert Park",
    address: "Corner Twist and Wolmarans Streets, Joubert Park, Johannesburg",
    tel: ["011 725 4728"],
    openingTime: "8:00 AM",
    closingTime: "4:00 PM",
    Specialties: [],
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 5,
    name: "Jeppe",
    address: "34 Ford Street, Jeppestown, 2094",
    tel: ["011 614 1474", "011 614 1475", "011 614 1476"],
    openingTime: "8:00 AM",
    closingTime: "4:00 PM",
    Specialties: ["TB", "Psychiatry"],
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 6,
    name: "Esselen Street HIV/Aids Programme",
    address: "17 Esselen St, Hillbrow, Johannesburg, 2001",
    tel: ["011 725 6711", "011 725 6721"],
    openingTime: "8:00 AM",
    closingTime: "4:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 7,
    name: "Yeoville",
    address: "Corner Kenmere and Hopkins Streets, Yeoville, Johannesburg, 2198",
    tel: ["011 648 7979"],
    openingTime: "8:00 AM",
    closingTime: "4:00 PM",
    Specialties: ["TB"],
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 8,
    name: "Cardiac Rehabilitation and Exercise",
    address: "Wits Education Campus (JCE), St Andrews Road, Parktown",
    tel: ["011 717 3376", "011 717 3377"],
    openingTime: "7:00 AM",
    closingTime: "7:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 9,
    name: "Rosettenville",
    address: "1 Rose Avenue, Cnr Mabel Street, Rosettenville, 2190",
    tel: ["011 435 1045", "011 435 1046", "011 435 1047"],
    openingTime: "7:30 AM",
    closingTime: "4:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 10,
    name: "Glenanda",
    address: "Corner Vorster Avenue and Surmone Street, Glenanda",
    tel: ["011 432 3546"],
    openingTime: "7:30 AM",
    closingTime: "3:30 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: "info@glenandamedicalcentre.co.za",
    website: null, // Facebook page provided instead
  },
  {
    id: 11,
    name: "South Hills",
    address:
      "Corner Geneva and Estantia Roads, Welfare Park, Johannesburg South, 2197",
    tel: ["011 623 1297"],
    openingTime: "7:30 AM",
    closingTime: "4:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 12,
    name: "Crown Gardens",
    address:
      "Recreation Centre, Cnr Ulster and Mourne Streets, Crown Gardens, Johannesburg South, 2091",
    tel: ["011 433 2351"],
    openingTime: "8:00 AM",
    closingTime: "4:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 13,
    name: "Bellavista",
    address: "Corner Zietsman and Alex Streets, Bellavista",
    tel: ["011 433 1593"],
    openingTime: "7:30 AM",
    closingTime: "2:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 14,
    name: "Malvern",
    address: "501 – 505 Malvern Plaza, Malvern",
    tel: ["011 622 1245"],
    openingTime: "7:30 AM",
    closingTime: "4:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 15,
    name: "Kibler Park",
    address: "Corner Kenneth Gardens and Summer Place, Kibler Park, 2091",
    tel: ["011 943 2002"],
    openingTime: "7:30 AM",
    closingTime: "4:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 16,
    name: "Crosby Clinic",
    address: "Stand 1629, 77 Ingelby Street, Crosby",
    tel: ["011 837 9118", "011 837 9119"],
    openingTime: "7:30 AM",
    closingTime: "4:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 17,
    name: "Jeppe Street Clinic",
    address:
      "1429 Johannesburg 159 Rahima Moosa Street (previously Jeppe Street), Jeppe Street, Johannesburg",
    tel: ["011 336 0517"],
    openingTime: "7:00 AM",
    closingTime: "4:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    id: 18,
    name: "Bezvalley Clinic",
    address: "1316 Bezuidenhout Valley, Cnr 6th Street & 4th Ave, Bezvalley",
    tel: ["011 648 0617"],
    openingTime: "7:30 AM",
    closingTime: "4:00 PM",
    Specialties: [], // Not provided
    isClinic: true,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
];

const hospitals = [
  {
    name: "Life Bedford Gardens Hospital",
    address: "7 Leicester Road, Bedford Gardens, Bedfordview, 2008",
    tel: "011 677 8500",
    openingTime: null, // Not provided
    closingTime: null, // Not provided
    Specialties: [], // Not provided
    isClinic: false,
    public: true,
    open24Hours: false, // Not provided
    email: "Nozuko.Daweti@lifehealthcare.co.za",
    website:
      "https://www.lifehealthcare.co.za/hospitals/gauteng/johannesburg/life-bedford-gardens-hospital/",
  },
  {
    name: "Life Brackenview",
    address: "22 De Waal Street, Brackendowns, Alberton",
    tel: "010 009 6200",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: false,
    email: [
      "info.brackenview@lifehealthcare.co.za",
      "ashni.Padiachey@lifehealthcare.co.za",
    ],
    website:
      "https://www.lifehealthcare.co.za/hospitals/gauteng/johannesburg/life-brackenview/",
  },
  {
    name: "Life Brenthurst Hospital",
    address: "4 Park Lane, Parktown, Johannesburg, 2193",
    tel: "011 647 9000",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: false,
    email: "Brenthurst.Communication@lifehealthcare.co.za",
    website:
      "https://www.lifehealthcare.co.za/hospitals/gauteng/johannesburg/life-brenthurst-hospital/",
  },
  {
    name: "Chris Hani Baragwanath Hospital",
    address: "26 Chris Hani Road, Bertsham, Johannesburg",
    tel: "011 933 8000",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: false,
    email: null,
    website: "http://www.chrishanibaragwanathhospital.co.za/",
  },
  {
    name: "Helen Joseph Hospital",
    address: "1 Perth Road, Auckland Park, Johannesburg",
    tel: "011 489 1011",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: true,
    email: null,
    website: null,
  },
  {
    name: "Charlotte Maxeke Johannesburg Academic Hospital",
    address: "17 Jubilee Road, Parktown, Johannesburg",
    tel: "011 488 4911",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: true,
    email: "Angy.Mokgothu@gauteng.gov.za",
    website: null, // Facebook page provided instead
  },
  {
    name: "Rahima Moosa Mother and Child Hospital",
    address: "Fule Street & Oudtshoorn Street, Newclare, Johannesburg",
    tel: "011 470 9000",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    name: "Edenvale General Hospital",
    address: "Modderfontein Road, Edenvale, Johannesburg",
    tel: "011 321 6000",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    name: "Tambo Memorial Hospital",
    address: "Railway Street, Boksburg, Johannesburg",
    tel: "011 898 8000",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    name: "Lenasia South Hospital",
    address: "Marlin Avenue, Lenasia South, Johannesburg",
    tel: "011 213 2000",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    name: "South Rand Hospital",
    address: "Friars Hill Road, Rosettenville, Johannesburg South",
    tel: "011 435 0022",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    name: "Tembisa Hospital",
    address: "Industry Road, Olifantsfontein, Tembisa",
    tel: "011 923 2000",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: true,
    open24Hours: false,
    email: null,
    website: null,
  },
  {
    name: "Far East Rand Hospital",
    address: "Hospital Street, Springs, Johannesburg",
    tel: "011 812 8300",
    openingTime: null,
    closingTime: null,
    Specialties: [],
    isClinic: false,
    public: false,
    open24Hours: false,
    email: null,
    website: null,
  },
];

const announcements = [
  {
    messageID: 1,
    title: "Flu Vaccine Stock Update",
    details:
      "We are pleased to inform you that our clinic has received a new stock of flu vaccines. You can book your appointment for the flu shot starting next Monday.",
    time: "2024-07-25 10:30:00",
    id: 101,
  },
  {
    messageID: 2,
    title: "Change in Operating Hours",
    details:
      "Please note that our clinic will be operating from 9:00 AM to 5:00 PM on Friday, August 2nd, due to staff training.",
    time: "2024-07-26 09:00:00",
    id: 102,
  },
  {
    messageID: 3,
    title: "New Specialist Joining Our Team",
    details:
      "We are excited to announce that Dr. Emily Chang, a renowned pediatrician, will be joining our clinic starting September 1st. Bookings for pediatric consultations are now open.",
    time: "2024-07-27 14:00:00",
    id: 103,
  },
  {
    messageID: 4,
    title: "COVID-19 Testing Availability",
    details:
      "Our clinic continues to offer COVID-19 testing every Tuesday and Thursday. Please book an appointment online or call our reception for more details.",
    time: "2024-07-28 08:45:00",
    id: 104,
  },
  {
    messageID: 5,
    title: "Upcoming Health Workshop",
    details:
      "Join us for a free health workshop on 'Managing Diabetes' on Saturday, August 5th, from 10:00 AM to 12:00 PM. Register at the front desk to secure your spot.",
    time: "2024-07-29 11:15:00",
    id: 105,
  },
  {
    messageID: 6,
    title: "New Appointment Booking System",
    details:
      "We have launched a new online appointment booking system to improve your experience. Visit our website to book your appointments with ease.",
    time: "2024-07-30 16:00:00",
    id: 106,
  },
  {
    messageID: 7,
    title: "Temporary Closure for Renovation",
    details:
      "Please be informed that our clinic will be closed for renovations from August 15th to August 20th. We apologize for any inconvenience caused.",
    time: "2024-07-31 13:30:00",
    id: 107,
  },
  {
    messageID: 8,
    title: "Blood Donation Camp",
    details:
      "Join us for our annual blood donation camp on August 10th from 9:00 AM to 4:00 PM. Your participation can save lives!",
    time: "2024-08-01 12:01:01",
    id: 108,
  },
  {
    messageID: 9,
    title: "Special Discount on Health Check-ups",
    details:
      "Throughout August, we are offering a 20% discount on all comprehensive health check-up packages. Book your appointment today.",
    time: "2024-08-02 10:00:00",
    id: 109,
  },
  {
    messageID: 10,
    title: "Free Nutrition Consultation",
    details:
      "We are offering free nutrition consultations with our dietician every Wednesday in August. Call us to schedule your session.",
    time: "2024-08-03 09:30:00",
    id: 110,
  },
  {
    messageID: 11,
    title: "Health Insurance Partnership Announcement",
    details:
      "We are pleased to announce our partnership with ABC Health Insurance, offering more coverage options for our patients.",
    time: "2024-08-04 14:45:00",
    id: 111,
  },
  {
    messageID: 12,
    title: "Update on Appointment Cancellations",
    details:
      "Due to high demand, please cancel appointments at least 24 hours in advance to avoid any charges. Thank you for your cooperation.",
    time: "2024-08-05 11:00:00",
    id: 112,
  },
  {
    messageID: 13,
    title: "Mental Health Awareness Campaign",
    details:
      "Join us for a series of talks and workshops on mental health from August 12th to August 14th. Open to all community members.",
    time: "2024-08-06 15:20:00",
    id: 113,
  },
  {
    messageID: 14,
    title: "Annual Staff Training Day",
    details:
      "Our clinic will be closed on August 18th for our annual staff training day. We appreciate your understanding and support.",
    time: "2024-08-07 13:00:00",
    id: 114,
  },
  {
    messageID: 15,
    title: "Women's Health Screening Event",
    details:
      "We are hosting a Women's Health Screening event on August 20th from 9:00 AM to 3:00 PM. Book your spot now for early detection screenings.",
    time: "2024-08-08 12:30:00",
    id: 115,
  },
];

export { clinics, hospitals, announcements };
